/*
	Author	: Jonathan Durbin
	Course	: IST659
	Term	: April 2021
*/

CREATE DATABASE [IST659-Project]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'IST659-Project', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\IST659-Project.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'IST659-Project_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\IST659-Project_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [IST659-Project] SET COMPATIBILITY_LEVEL = 150
GO
ALTER DATABASE [IST659-Project] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [IST659-Project] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [IST659-Project] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [IST659-Project] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [IST659-Project] SET ARITHABORT OFF 
GO
ALTER DATABASE [IST659-Project] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [IST659-Project] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [IST659-Project] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [IST659-Project] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [IST659-Project] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [IST659-Project] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [IST659-Project] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [IST659-Project] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [IST659-Project] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [IST659-Project] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [IST659-Project] SET  DISABLE_BROKER 
GO
ALTER DATABASE [IST659-Project] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [IST659-Project] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [IST659-Project] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [IST659-Project] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [IST659-Project] SET  READ_WRITE 
GO
ALTER DATABASE [IST659-Project] SET RECOVERY FULL 
GO
ALTER DATABASE [IST659-Project] SET  MULTI_USER 
GO
ALTER DATABASE [IST659-Project] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [IST659-Project] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [IST659-Project] SET DELAYED_DURABILITY = DISABLED 
GO
USE [IST659-Project]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [IST659-Project]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [IST659-Project] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
